[api_keys]
deepseek = "sk-9867e199ef484c9bb4cf70ef846b39ce"
binance_key = "YiKdsN8BmShpy6klh3799G44ULjDgJGLtK6021qyptdZgUMiVdYyEuGAJj3VBAKZ"
binance_secret = "3Ia7PX1K94XCqNGafZgA1yomeKsLc9OdWuGGFwkIzrkkxhNnZsWqm8r5TY7UE9s1"
